services:
  tab.webapi:
    image: ${DOCKER_REGISTRY-}tabwebapi
    build:
      context: .
      dockerfile: src/TAB.WebApi/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    networks:
    - tab
    ports:
    - "7194:80"
    depends_on:
    - tab.sqlserver
  tab.sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
    - "1433:1433"
    networks:
    - tab
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=hamood12344321#
    volumes:  
    - tab.sqlserver:/var/opt/mssql

volumes:
  tab.sqlserver:

networks:
  tab:
    driver: bridge