version: '3.8'

services:
  tab.webapi:
    image: ${DOCKER_REGISTRY-}tabwebapi
    build:
      context: .
      dockerfile: src/TAB.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - tab
    ports:
      - "7072:80"
      - "443:443" 
    depends_on:
      - tab.sqlserver
    volumes:
      - tab.api:/app/wwwroot  

  tab.sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    networks:
      - tab
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:  
      - tab.sqlserver:/var/opt/mssql

volumes:
  tab.sqlserver:
  tab.api:

networks:
  tab:
    driver: bridge
