version: '3.8'

services:
  tab.webapi:
    image: ${DOCKER_REGISTRY-}tabwebapi
    build:
      context: .
      dockerfile: src/TAB.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - tab
    ports:
      - "7194:80"
    depends_on:
      - tab.sqlserver
    volumes:
      - tap.api:/app/wwwroot

  tab.sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    networks:
      - tab
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:  
      - tab.sqlserver:/var/opt/mssql

volumes:
  tab.sqlserver:
  tap.api:

networks:
  tab:
    driver: bridge
