name: Publish to Azure Web App
on:
  workflow_dispatch:
  push:
    branches:
      - develop
env:
  AZURE_WEBAPP_NAME: foothill-tab
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - name: Restore dependencies
      run: dotnet restore ./tab.sln

    - name: Build
      run: dotnet build ./tab.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ./tests/Application.UnitTests/Application.UnitTests.csproj --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish ./src/TAB.WebApi/TAB.WebApi.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/TAB.WebApi'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/TAB.WebApi
        publish-profile: "${{ secrets.AZURE_PUBLISH_PROFILE }}"