name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  AZURE_WEBAPP_NAME: foothill-tab
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - name: Restore dependencies
      run: dotnet restore ./tab.sln

    - name: Build
      run: dotnet build ./tab.sln --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test ./tests/Application.UnitTests/Application.UnitTests.csproj --configuration Release --no-restore

    - name: Run Architecture Tests
      run: dotnet test ./tests/ArchitectureTests/ArchitectureTests.csproj --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish ./src/TAB.WebApi/TAB.WebApi.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_REGISTRY }}/your-username/tabwebapi ./src/TAB.WebApi

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/mohammadhmoudah/foothill-tab:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
